# -*- coding: utf-8 -*-
"""AnaliseExploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1egL9MStm2Z5djgdFzXR90XBm_at70aMT
"""

#Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#Upload do arquivo
from google.colab import files
arq = files.upload()

#Criando DataFrame
df = pd.read_excel("AdventureWorks.xlsx")

#Visualizando as 5 primeiras linhas
df.head()

#Quantidade de linhas e colunas
df.shape

#Verificando os tipo de Dados
df.dtypes

#Qual é a receita total?
df["Valor Venda"].sum()

#Qual o custo total?
df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head()

df = df.drop(columns = ["custo"])

round(df["Custo"].sum(),2)

#Qual é o lucro total?
df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head()

round(df["Lucro"].sum(), 2)

#Criando uma coluna para de tempo de envio
df["Tempo Envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

#Média de tempo de envio do produto para cada marca
df["Tempo Envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.groupby("Marca")["Tempo Envio"].mean()

#Verificando se há dados faltante
df.isnull().sum()

#Lucro por ano
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

pd.options.display.float_format = '{:20,.2f}'.format

#Resetando o index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

#Qual o total de produtos vendidos?
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending = False)

#Gráfico do total de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending = True).plot.barh(title = "Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto")

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title = "Lucro Anual")
plt.xlabel("Ano")
plt.ylabel("Receita")

#Vendas somente de 2009
df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.head()

df_2009.groupby(df["Data Venda"].dt.month)["Lucro"].sum().plot(title = "Lucro Mensal")
plt.xlabel("Mês")
plt.ylabel("Receita")

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title = "Lucro por Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation = "horizontal");

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title = "Lucro por Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation = "horizontal");

df["Tempo Envio"].describe()

#Gráfico de boxplot
plt.boxplot(df["Tempo Envio"]);

#Histograma
plt.hist(df["Tempo Envio"]);

#Identificando o outliers
df[df["Tempo Envio"]== 20]